### ISSUE TITLE
did:v1:test:nym:z6MkuYhA5TN5XGyvFhjhLjBkJ19hY2HnQgwe7h5q1NkK5bjf is not resolvable

### ISSUE THREAD

**Issue by fqutishat** [decentralized-identity/universal-resolver#88]
Go to https://uniresolver.io/ and try to resolve did:v1:test:nym:z6MkuYhA5TN5XGyvFhjhLjBkJ19hY2HnQgwe7h5q1NkK5bjf from Examples

**Comment by fqutishat** [comment]
@philpotisk

**Comment by OR13** [comment]
I believe this may be related to the hostname / config mapping for did:v1

https://github.com/decentralized-identity/universal-resolver/blob/master/config.json#L27

**Comment by OR13** [comment]
There appears to be an aggressive redirect for https://frankfurt.capybara.veres.one/dids/did:v1:test:nym:z6MkuYhA5TN5XGyvFhjhLjBkJ19hY2HnQgwe7h5q1NkK5bjf

**Comment by fqutishat** [comment]
@peacekeeper

**Comment by peacekeeper** [comment]
I recently updated the `did:v1` driver configuration to align with an upgrade in Veres One's did-cli tool: https://github.com/digitalbazaar/did-cli/commit/426d68760c37e2f02fdf33e3d3db1aa5380a3cbc. This changed the Veres One testnet from a `*.bee.veres.one` to `*.capybara.veres.one` network. Maybe @msporny can add more background.

I don't think existing DIDs were migrated from the old testnet to the new testnet. Also, as far as I know, there is no way for a resolver to tell which network to use (it's not encoded in the DID itself).

> or I need to make that request with custom headers / not from a normal browser.

That's correct, you can try it from the command line as follows:

```
curl -X GET --header 'Accept: application/ld+json' https://genesis.bee.veres.one/dids/did:v1:test:nym:z6MkuYhA5TN5XGyvFhjhLjBkJ19hY2HnQgwe7h5q1NkK5bjf
```

(the above is the DID you mentioned, on the old "bee" network)

```
curl -X GET --header 'Accept: application/ld+json' https://frankfurt.capybara.veres.one/dids/did:v1:test:nym:z6MkgF4uJbLMoUin2uKaBf4Jb1F7SHzuALE8Ldq8FPPpHE9t
```

(the above is a DID on the new "capybara" network)

I just fixed the examples in https://github.com/decentralized-identity/universal-resolver/commit/39b706f1431fee2ca72b389c17f5968caa129a68 and https://github.com/decentralized-identity/universal-resolver-frontend/commit/b986a5b3d1fadbe470ef0f23f1463ee92971da98.

**Comment by msporny** [comment]
> This changed the Veres One testnet from a *.bee.veres.one to *.capybara.veres.one network. Maybe @msporny can add more background.

Yes, we launched the newest Veres One Testnet (Cavy Capybara) last week and upgraded all the default tooling to use the new testnet. 

The old testnet still exists and can be used using the legacy toolchain. As with all Veres One Testnet releases, we don't migrate DIDs and we don't provide backwards compatability to new testnets. This will, of course, not be the case for the live network once it's launched (we will provide full continuity for DIDs for all upgrades). The old testnet will be decommissioned in time, we try to do it within a month of the new testnet launch, but sometimes delay decommissioning if there are people that depend on the old testnet (and let us know).

At this point, we believe that we are API and data model stable... but that can change based on decisions made in the DID WG since Veres One is targeting 100% compliance with the W3C DID Core specification.

Please don't announce this yet, give us time to make the announcement in the W3C Veres One Community Group: https://www.w3.org/community/veres-one/

**Comment by msporny** [comment]
> There appears to be an aggressive redirect for https://frankfurt.capybara.veres.one/dids/did:v1:test:nym:z6MkuYhA5TN5XGyvFhjhLjBkJ19hY2HnQgwe7h5q1NkK5bjf
> or I need to make that request with custom headers / not from a normal browser.

Your browser is asking for HTML, and that endpoint is like "I can't help you there, go here if you want human readable stuff". :)

We should probably update Veres One nodes to return some human readable form of the DID Document for the URL you mention above. Just a simple matter of writing a few hundred lines of code... we'll get to it in time... but for now, you have to do what @peacekeeper mentioned above:

> curl -H 'Accept: application/ld+json' https://frankfurt.capybara.veres.one/dids/did:v1:test:nym:z6MkgF4uJbLMoUin2uKaBf4Jb1F7SHzuALE8Ldq8FPPpHE9t
